[keybinds]
append_item = "o"
delete_item = "dd"
down = "j"
edit = "i"
edit_append = "A"
edit_substitute = "S"
jump_bottom = "G"
jump_top = "gg"
next_match = "n"
normal_mode = "Esc"
prepend_item = "O"
previous_match = "N"
quit = ":q"
save = ":w"
search = "/"
undo = "u"
up = "k"

[theme]
bg_active = "#a6e3a1"
bg_highlight = "#89b4fa"
bg_normal = "#1e1e2e"
bg_search = "#cba6f7"
border_active = "#a6e3a1"
border_normal = "#45475a"
fg_accent = "#b4befe"
fg_dimmed = "#6c7086"
fg_highlight = "#1e1e2e"
fg_modified = "#fab387"
fg_normal = "#cdd6f4"
fg_warning = "#f38ba8"
transparent = true
tree_depth_1 = "#b4befe"
tree_depth_2 = "#cba6f7"
tree_depth_3 = "#89b4fa"
tree_depth_4 = "#fab387"
